
package WS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns WS.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCmpt", targetNamespace = "http://ws/", className = "WS.GetCmpt")
    @ResponseWrapper(localName = "getCmptResponse", targetNamespace = "http://ws/", className = "WS.GetCmptResponse")
    @Action(input = "http://ws/BanqueService/getCmptRequest", output = "http://ws/BanqueService/getCmptResponse")
    public Compte getCmpt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroDH", targetNamespace = "http://ws/", className = "WS.ConversionEuroDH")
    @ResponseWrapper(localName = "ConversionEuroDHResponse", targetNamespace = "http://ws/", className = "WS.ConversionEuroDHResponse")
    @Action(input = "http://ws/BanqueService/ConversionEuroDHRequest", output = "http://ws/BanqueService/ConversionEuroDHResponse")
    public double conversionEuroDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<WS.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompte", targetNamespace = "http://ws/", className = "WS.ListCompte")
    @ResponseWrapper(localName = "listCompteResponse", targetNamespace = "http://ws/", className = "WS.ListCompteResponse")
    @Action(input = "http://ws/BanqueService/listCompteRequest", output = "http://ws/BanqueService/listCompteResponse")
    public List<Compte> listCompte();

}
